In [1]:
import pandas as pd
#test

In [28]:
df1  = pd.read_csv('vgnew_awarded1.csv')
df2 = pd.read_csv('vgsales_1_class.csv')

In [29]:
df1 = df1[['Name','multiplayer','singleplayer','awarded']]

df4 = df1.drop_duplicates(subset=['Name'])

In [30]:
print(df1.shape)
print(df4.shape)

df3 = df4.merge(right= df2, on= 'Name', how= 'inner')

(16598, 4)
(11493, 4)

In [31]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(16598, 4)
(4256, 62)
(4256, 65)

In [32]:
df3 = df3.drop(['IP','multiplayer_y','singleplayer_y','videotitle'],axis = 1)

In [26]:
df3

,Name,multiplayer_x,singleplayer_x,awarded,multiplayer_y,singleplayer_y,viewconut,likecount,commentcount,videotitle,...,Platform_XOne,Platform_NS,Platform_PS5,Platform_XS,Platform_ST,Publisher_class,Developer_class,IP_class,Sales_label_q4,Sales_label_q10
0,Wii Sports,True,True,1.0,True,True,45473.0,400.0,79.0,Wii Sports Nintendo Wii Video - Video Review,...,0,0,0,0,0,4,4,2,3,9
1,Mario Kart Wii,True,True,1.0,True,True,241260.0,1487.0,682.0,Mario Kart Wii Review,...,0,0,0,0,0,4,4,3,3,9
2,Wii Sports Resort,True,True,0.0,True,True,1532660.0,2514.0,947.0,Wii Sports Resort Review,...,0,0,0,0,0,4,4,2,3,9
3,Tetris,True,True,1.0,True,True,258749.0,3341.0,472.0,Tetris Effect Review,...,0,0,0,0,0,0,0,2,3,9
4,New Super Mario Bros.,True,True,0.0,True,True,1002608.0,11057.0,1649.0,New Super Mario Bros. U Deluxe Review,...,0,0,0,0,0,4,4,3,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,Kessen,False,True,0.0,False,True,236.0,0.0,0.0,Kessen PlayStation 2 Gameplay_2000_01_28,...,0,0,0,0,0,4,2,0,2,6
1060,Yu-Gi-Oh! Worldwide Edition: Stairway to the D...,True,True,0.0,True,True,4116.0,17.0,3.0,Yu-Gi-Oh! Destiny Board Traveler Game Boy Game...,...,0,0,0,0,0,4,2,2,2,6
1061,Guitar Hero: Metallica,True,True,0.0,True,True,132637.0,768.0,335.0,Guitar Hero: Metallica Video Review,...,0,0,0,0,0,4,2,2,3,8
1063,Army of Two: The 40th Day,True,True,0.0,True,True,491273.0,1967.0,940.0,Army of Two: The 40th Day Review,...,0,0,0,0,0,4,0,0,3,8
1064,Wii Play: Motion,True,True,0.0,True,True,10096.0,77.0,17.0,Wii Play (with Wii Remote) Nintendo Wii Review...,...,0,0,0,0,0,4,0,2,2,6

In [33]:
df3 = df3.dropna()
df3["multiplayer_x"] = df3["multiplayer_x"].astype(int)
df3["singleplayer_x"] = df3["singleplayer_x"].astype(int)

In [34]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 866 entries, 0 to 1064
Data columns (total 61 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     866 non-null    object
 1   multiplayer_x            866 non-null    int64
 2   singleplayer_x           866 non-null    int64
 3   awarded                  866 non-null    float64
 4   viewconut                866 non-null    float64
 5   likecount                866 non-null    float64
 6   commentcount             866 non-null    float64
 7   published                866 non-null    object
 8   Global_Sales             866 non-null    float64
 9   Genre__Action-Adventure  866 non-null    int64
 10  Genre__Adventure         866 non-null    int64
 11  Genre__Board+Game        866 non-null    int64
 12  Genre__Education         866 non-null    int64
 13  Genre__Fighting          866 non-null    int64
 14  Genre__MMO               866 non-null    int64
 15  Genre__Misc              866 non-null    int64
 16  Genre__Music             866 non-null    int64
 17  Genre__Party             866 non-null    int64
 18  Genre__Platform          866 non-null    int64
 19  Genre__Puzzle            866 non-null    int64
 20  Genre__Racing            866 non-null    int64
 21  Genre__Role-Playing      866 non-null    int64
 22  Genre__Shooter           866 non-null    int64
 23  Genre__Simulation        866 non-null    int64
 24  Genre__Sports            866 non-null    int64
 25  Genre__Strategy          866 non-null    int64
 26  Genre__Visual+Novel      866 non-null    int64
 27  Release_date             866 non-null    object
 28  Meta_Critic_Score        866 non-null    float64
 29  Meta_User_Score          866 non-null    float64
 30  Publisher                866 non-null    object
 31  Developer                866 non-null    object
 32  N_Critic_Reviews         866 non-null    int64
 33  N_User_Reviews           866 non-null    int64
 34  Platform_PC              866 non-null    int64
 35  Platform_N64             866 non-null    int64
 36  Platform_PlayStation     866 non-null    int64
 37  Platform_DC              866 non-null    int64
 38  Platform_PS2             866 non-null    int64
 39  Platform_XB              866 non-null    int64
 40  Platform_GBA             866 non-null    int64
 41  Platform_GC              866 non-null    int64
 42  Platform_NDS             866 non-null    int64
 43  Platform_X360            866 non-null    int64
 44  Platform_PSP             866 non-null    int64
 45  Platform_NWii            866 non-null    int64
 46  Platform_PS3             866 non-null    int64
 47  Platform_3DS             866 non-null    int64
 48  Platform_PSV             866 non-null    int64
 49  Platform_WiiU            866 non-null    int64
 50  Platform_PS4             866 non-null    int64
 51  Platform_XOne            866 non-null    int64
 52  Platform_NS              866 non-null    int64
 53  Platform_PS5             866 non-null    int64
 54  Platform_XS              866 non-null    int64
 55  Platform_ST              866 non-null    int64
 56  Publisher_class          866 non-null    int64
 57  Developer_class          866 non-null    int64
 58  IP_class                 866 non-null    int64
 59  Sales_label_q4           866 non-null    int64
 60  Sales_label_q10          866 non-null    int64
dtypes: float64(7), int64(49), object(5)
memory usage: 419.5+ KB

In [35]:
print(df3.shape)
df3 = df3.drop(['Release_date','Publisher','Developer','Global_Sales','published'],axis = 1)

(866, 61)

In [36]:
df3.set_index('Name',inplace = True)

In [37]:
from sklearn import ensemble
from sklearn.model_selection import train_test_split
df5 = df3.drop('Sales_label_q10',axis = 1)
target = df5.iloc[:,-1]

In [38]:
data = df5.drop('Sales_label_q4',axis = 1)

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 866 entries, Wii Sports to Wii Play: Motion
Data columns (total 53 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   multiplayer_x            866 non-null    int64
 1   singleplayer_x           866 non-null    int64
 2   awarded                  866 non-null    float64
 3   viewconut                866 non-null    float64
 4   likecount                866 non-null    float64
 5   commentcount             866 non-null    float64
 6   Genre__Action-Adventure  866 non-null    int64
 7   Genre__Adventure         866 non-null    int64
 8   Genre__Board+Game        866 non-null    int64
 9   Genre__Education         866 non-null    int64
 10  Genre__Fighting          866 non-null    int64
 11  Genre__MMO               866 non-null    int64
 12  Genre__Misc              866 non-null    int64
 13  Genre__Music             866 non-null    int64
 14  Genre__Party             866 non-null    int64
 15  Genre__Platform          866 non-null    int64
 16  Genre__Puzzle            866 non-null    int64
 17  Genre__Racing            866 non-null    int64
 18  Genre__Role-Playing      866 non-null    int64
 19  Genre__Shooter           866 non-null    int64
 20  Genre__Simulation        866 non-null    int64
 21  Genre__Sports            866 non-null    int64
 22  Genre__Strategy          866 non-null    int64
 23  Genre__Visual+Novel      866 non-null    int64
 24  Meta_Critic_Score        866 non-null    float64
 25  Meta_User_Score          866 non-null    float64
 26  N_Critic_Reviews         866 non-null    int64
 27  N_User_Reviews           866 non-null    int64
 28  Platform_PC              866 non-null    int64
 29  Platform_N64             866 non-null    int64
 30  Platform_PlayStation     866 non-null    int64
 31  Platform_DC              866 non-null    int64
 32  Platform_PS2             866 non-null    int64
 33  Platform_XB              866 non-null    int64
 34  Platform_GBA             866 non-null    int64
 35  Platform_GC              866 non-null    int64
 36  Platform_NDS             866 non-null    int64
 37  Platform_X360            866 non-null    int64
 38  Platform_PSP             866 non-null    int64
 39  Platform_NWii            866 non-null    int64
 40  Platform_PS3             866 non-null    int64
 41  Platform_3DS             866 non-null    int64
 42  Platform_PSV             866 non-null    int64
 43  Platform_WiiU            866 non-null    int64
 44  Platform_PS4             866 non-null    int64
 45  Platform_XOne            866 non-null    int64
 46  Platform_NS              866 non-null    int64
 47  Platform_PS5             866 non-null    int64
 48  Platform_XS              866 non-null    int64
 49  Platform_ST              866 non-null    int64
 50  Publisher_class          866 non-null    int64
 51  Developer_class          866 non-null    int64
 52  IP_class                 866 non-null    int64
dtypes: float64(6), int64(47)
memory usage: 365.3+ KB

In [40]:
X_train,X_test,y_train,y_test = train_test_split(data,target,test_size = 0.2,random_state = 12)

In [41]:
clf= ensemble.RandomForestClassifier(n_jobs = -1,random_state = 321)
clf.fit(X_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=321)

In [42]:
y_pred = clf.predict(X_test)
pd.crosstab(y_test,y_pred,rownames =['reel'],colnames = ['predict'] )
pd.crosstab(y_test, y_pred, rownames=['Classe réelle'], colnames=['Classe prédite'])

Classe prédite  2    3
Classe réelle
2               2   30
3               1  141

In [43]:
print('score test',clf.score(X_test,y_test))
print('score train',clf.score(X_train,y_train))

score test 0.8218390804597702
score train 1.0

In [44]:
df3.to_csv('wiki_metacritics_yt.csv')